### PR TITLE
fully updated data labels

### PR DESCRIPTION
**Pull request by samudzi**
Tested this locally, labels working as desired

### CODE REVIEW

**Comment by samudzi** [comment]
Everything completed, just need to finish up the pull request

**Comment by davidtamaki** [comment]
Thanks @samudzi. It looks like this is breaking the data labels and legend when the `.each` loop hits an angle > 180 degrees:
image

Adding the following code [here](https://github.com/davidtamaki/aster_plot/pull/1/commits/682ef4cbd71f369e539c0669e94f3934c96de416#diff-6ef38ba718a66d59120d148f9fa846baR366) will help it fail gracefully:

```              
if (endLoc.exec( newArc ) == null || startLoc.exec( newArc ) == null || middleLoc.exec( newArc ) == null) { 
                return false; 
              }
```
Is there anyway you could tweak the code to handle these edge cases?

**Comment by samudzi** [comment]
Will work on that today.  Having Jean test my initial changes to id any other quirky edge cases, and then will wrap up based on their feedback

**Comment by davidtamaki** [comment]
Awesome - looks great 👍

**Pull request merged**
